name: Pull Request CI

on:
  pull_request:
    branches: ['*']

env:
  API_PORT: 0
  DOMAIN_URL: ${{ vars.DEPLOY_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: env
        run: cp .env.example .env

      - name: build
        run: make build

#       - name: test
#         run: echo "Running tests..."
